import { countBy } from 'underscore';

export interface Children {
	title?: string;
	older?: string;
	young?: string;
	compare?: string | string[];
}

export interface Title {
	title: string;
	classify: string;
	alias?: string;
	father?: string;
	mother?: string;
	husband?: string;
	wife?: string;
	exHusband?: string;
	exWife?: string;
	son?: Children;
	daughter?: Children;
}

export const TITLE_DEFAULT: Title[] = [
	{title: '本人', father: '父亲', mother: '母亲', husband: '丈夫', wife: '妻子', exHusband: '前夫', exWife: '前妻',
		son: {title: '儿子'}, daughter: {title: '女儿'},
		classify: '宗亲',
	},
	{title: '丈夫', father: '公公', mother: '婆婆', wife: '妻子', exWife: '前妻',
		son: {title: '儿子'}, daughter: {title: '女儿'},
		classify: '宗亲', alias: '先生',
	},
	{title: '妻子', father: '岳父', mother: '岳母', husband: '丈夫', exHusband: '前夫',
		son: {title: '儿子'}, daughter: {title: '女儿'},
		classify: '宗亲', alias: '老婆, 内人',
	},
	{title: '父亲', father: '祖父', mother: '祖母', wife: '母亲', exWife: '阿姨',
		son: {older: '哥哥', young: '弟弟', compare: '本人'}, daughter: {older: '姐姐', young: '妹妹', compare: '本人'},
		classify: '宗亲', alias: '爸爸, 爹',
	},
	{title: '母亲', father: '外公', mother: '外婆', husband: '父亲', exHusband: '叔叔',
		son: {older: '哥哥', young: '弟弟', compare: '本人'}, daughter: {older: '姐姐', young: '妹妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '公公', father: '祖父', mother: '祖母', wife: '婆婆',
		son: {older: '大伯子', young: '小叔子', compare: '丈夫'}, daughter: {older: '大姑子', young: '小姑子', compare: '丈夫'},
		classify: '宗亲',
	},
	{title: '岳父', father: '祖父', mother: '祖母', wife: '岳母',
		son: {older: '大舅子', young: '小舅子', compare: '妻子'}, daughter: {older: '大姨子', young: '小姨子', compare: '妻子'},
		classify: '妻亲', alias: '岳丈, 老丈人, 泰山, 外父',
	},
	{title: '祖父', father: '曾祖父', mother: '曾祖母', wife: '祖母', exWife: '阿婆',
		son: {older: '伯父', young: '叔父', compare: ['父亲', '公公', '岳父']}, daughter: {title: '姑母'},
		classify: '宗亲', alias: '爷爷, 太爷',
	},
	{title: '曾祖父', father: '高祖父', mother: '高祖母', wife: '曾祖母',
		son: {older: '伯祖父', young: '叔祖父', compare: '祖父'}, daughter: {title: '祖姑'},
		classify: '宗亲', alias: '太爷, 三世祖',
	},
	{title: '高祖父', father: '天祖父', mother: '天祖母',  wife: '高祖母',
		son: {older: '曾伯祖父', young: '曾叔祖父', compare: '曾祖父'}, daughter: {title: '曾祖姑'},
		classify: '宗亲',
	},
	{title: '天祖父', father: '列祖父', mother: '列祖母',  wife: '天祖母',
		son: {older: '高伯祖父', young: '高叔祖父', compare: '高祖父'}, daughter: {title: '高祖姑'},
		classify: '宗亲',
	},
	{title: '列祖父', father: '太祖父', mother: '太祖母',  wife: '列祖母',
		son: {older: '天伯祖父', young: '天叔祖父', compare: '天祖父'}, daughter: {title: '天祖姑'},
		classify: '宗亲',
	},
	{title: '太祖父', father: '远祖父', mother: '远祖母',  wife: '太祖母',
		son: {older: '列伯祖父', young: '列叔祖父', compare: '列祖父'}, daughter: {title: '列祖姑'},
		classify: '宗亲',
	},
	{title: '远祖父', father: '鼻祖父', mother: '鼻祖母',  wife: '远祖母',
		son: {older: '太伯祖父', young: '太叔祖父', compare: '太祖父'}, daughter: {title: '太祖姑'},
		classify: '宗亲',
	},
	{title: '儿子', father: '丈夫', mother: '妻子', wife: '儿媳',
		son: {title: '孙子'}, daughter: {title: '孙女'},
		classify: '宗亲',
	},
	{title: '孙子', father: '儿子', mother: '儿媳', wife: '孙媳',
		son: {title: '曾孙'}, daughter: {title: '曾孙女'},
		classify: '宗亲',
	},
	{title: '孙女', father: '儿子', mother: '儿媳', husband: '孙女婿',
		son: {title: '曾外孙'}, daughter: {title: '曾外孙女'},
		classify: '宗亲',
	},
	{title: '曾孙', father: '孙子', mother: '孙媳', wife: '曾孙媳',
		son: {title: '玄孙'}, daughter: {title: '玄孙女'},
		classify: '宗亲',
	},
	{title: '曾孙女', father: '孙子', mother: '孙媳', husband: '曾孙女婿',
		son: {title: '玄外孙'}, daughter: {title: '玄外孙女'},
		classify: '宗亲',
	},
	{title: '玄孙', father: '曾孙', mother: '曾孙媳', wife: '玄孙媳',
		son: {title: '来孙'}, daughter: {title: '来孙女'},
		classify: '宗亲',
	},
	{title: '来孙', father: '玄孙', mother: '玄孙媳', wife: '来孙媳',
		son: {title: '晜孙'}, daughter: {title: '晜孙女'},
		classify: '宗亲',
	},
	{title: '晜孙', father: '来孙', mother: '来孙媳', wife: '晜孙媳',
		son: {title: '仍孙'}, daughter: {title: '仍孙女'},
		classify: '宗亲',
	},
	{title: '仍孙', father: '晜孙', mother: '晜孙媳', wife: '仍孙媳',
		son: {title: '云孙'}, daughter: {title: '云孙女'},
		classify: '宗亲',
	},
	{title: '云孙', father: '仍孙', mother: '仍孙媳', wife: '云孙媳',
		son: {title: '耳孙'}, daughter: {title: '耳孙女'},
		classify: '宗亲',
	},
	{title: '女儿', father: '丈夫', mother: '妻子', husband: '女婿',
		son: {title: '外孙'}, daughter: {title: '外孙女'},
		classify: '宗亲',
	},
	{title: '外孙', father: '女婿', mother: '女儿', wife: '外孙媳',
		son: {title: '曾外孙'}, daughter: {title: '曾外孙女'},
		classify: '外亲',
	},
	{title: '外孙女', father: '女婿', mother: '女儿', husband: '外孙女婿',
		son: {title: '曾外孙'}, daughter: {title: '曾外孙女'},
		classify: '外亲',
	},
	{title: '曾外孙', father: '外孙子', mother: '外孙媳', wife: '曾外孙媳',
		son: {title: '玄外孙'}, daughter: {title: '玄外孙女'},
		classify: '外亲',
	},
	{title: '曾外孙女', father: '外孙子', mother: '外孙媳', husband: '曾外孙女婿',
		son: {title: '玄外孙'}, daughter: {title: '玄外孙女'},
		classify: '外亲',
	},
	{title: '哥哥', father: '父亲', mother: '母亲', wife: '嫂子',
		son: {title: '侄子'}, daughter: {title: '侄女'},
		classify: '宗亲',
	},
	{title: '弟弟', father: '父亲', mother: '母亲', wife: '弟妹',
		son: {title: '侄子'}, daughter: {title: '侄女'},
		classify: '宗亲',
	},
	{title: '侄子', wife: '侄媳',
		son: {title: '侄孙'}, daughter: {title: '侄孙女'},
		classify: '宗亲',
	},
	{title: '侄女', husband: '侄女婿',
		son: {title: '侄外孙'}, daughter: {title: '侄外孙女'},
		classify: '宗亲',
	},
	{title: '姐姐', father: '父亲', mother: '母亲', husband: '姐夫',
		son: {title: '外甥'}, daughter: {title: '外甥女'},
		classify: '宗亲',
	},
	{title: '妹妹', father: '父亲', mother: '母亲', husband: '妹夫',
		son: {title: '外甥'}, daughter: {title: '外甥女'},
		classify: '宗亲',
	},
	{title: '外甥', wife: '外甥媳',
		son: {title: '外孙'}, daughter: {title: '外孙女'},
		classify: '外亲',
	},
	{title: '外甥女', husband: '外甥女婿',
		son: {title: '外孙'}, daughter: {title: '外孙女'},
		classify: '外亲',
	},
	{title: '伯父', father: '祖父', mother: '祖母', wife: '伯母',
		son: {older: '堂兄', young: '堂弟', compare: '本人'}, daughter: {older: '堂姐', young: '堂妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '叔父', father: '祖父', mother: '祖母', wife: '婶娘',
		son: {older: '堂兄', young: '堂弟', compare: '本人'}, daughter: {older: '堂姐', young: '堂妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '姑母', father: '祖父', mother: '祖母', husband: '姑父',
		son: {older: '表兄', young: '表弟', compare: '本人'}, daughter: {older: '表姐', young: '表妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '堂兄', wife: '堂嫂',
		son: {title: '堂侄'}, daughter: {title: '堂侄女'},
		classify: '宗亲',
	},
	{title: '堂弟', wife: '堂弟媳',
		son: {title: '堂侄'}, daughter: {title: '堂侄女'},
		classify: '宗亲',
	},
	{title: '堂姐', husband: '堂姐夫',
		son: {title: '从甥'}, daughter: {title: '从甥女'},
		classify: '宗亲',
	},
	{title: '堂妹', husband: '堂妹夫',
		son: {title: '从甥'}, daughter: {title: '从甥女'},
		classify: '宗亲',
	},
	{title: '从甥', wife: '从甥媳',
		son: {title: '从甥孙'}, daughter: {title: '从甥孙女'},
		classify: '外亲', alias: '堂外甥',
	},
	{title: '从甥女', husband: '从甥女婿',
		son: {title: '从甥外孙'}, daughter: {title: '从甥外孙女'},
		classify: '外亲', alias: '堂外甥女',
	},
	{title: '伯祖父', father: '曾祖父', mother: '曾祖母', wife: '伯祖母',
		son: {older: '堂伯父', young: '堂叔父', compare: '父亲'}, daughter: {title: '堂姑母'},
		classify: '宗亲',
	},
	{title: '叔祖父', father: '曾祖父', mother: '曾祖母', wife: '叔祖母',
		son: {older: '堂伯父', young: '堂叔父', compare: '父亲'}, daughter: {title: '堂姑母'},
		classify: '宗亲',
	},
	{title: '堂伯父', wife: '堂伯母',
		son: {older: '再从兄', young: '再从弟', compare: '本人'}, daughter: {older: '再从姐', young: '再从妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '堂叔父', wife: '堂叔母',
		son: {older: '再从兄', young: '再从弟', compare: '本人'}, daughter: {older: '再从姐', young: '再从妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '再从兄', wife: '再从嫂',
		son: {title: '再从侄'}, daughter: {title: '再从侄女'},
		classify: '宗亲',
	},
	{title: '再从弟', wife: '再从弟媳',
		son: {title: '再从侄'}, daughter: {title: '再从侄女'},
		classify: '宗亲',
	},
	{title: '再从姐', husband: '再从姐夫',
		son: {title: '再从外甥'}, daughter: {title: '再从外甥女'},
		classify: '宗亲',
	},
	{title: '再从妹', husband: '再从妹夫',
		son: {title: '再从外甥'}, daughter: {title: '再从外甥女'},
		classify: '宗亲',
	},
	{title: '曾伯祖父', father: '高祖父', mother: '高祖母', wife: '曾伯祖母',
		son: {older: '族伯祖父', young: '族叔祖父', compare: '祖父'}, daughter: {title: '族祖姑'},
		classify: '宗亲',
	},
	{title: '曾叔祖父', father: '高祖父', mother: '高祖母', wife: '曾叔祖母',
		son: {older: '族伯祖父', young: '族叔祖父', compare: '祖父'}, daughter: {title: '族祖姑'},
		classify: '宗亲',
	},
	{title: '族伯祖父', wife: '族伯祖母',
		son: {older: '族伯父', young: '族叔父', compare: '父亲'}, daughter: {title: '族姑母'},
		classify: '宗亲',
	},
	{title: '族叔祖父', wife: '族叔祖母',
		son: {older: '族伯父', young: '族叔父', compare: '父亲'}, daughter: {title: '族姑母'},
		classify: '宗亲',
	},
	{title: '族伯父', wife: '族伯母',
		son: {older: '族兄', young: '族弟', compare: '本人'}, daughter: {older: '族姐', young: '族妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '族叔父', wife: '族婶娘',
		son: {older: '族兄', young: '族弟', compare: '本人'}, daughter: {older: '族姐', young: '族妹', compare: '本人'},
		classify: '宗亲',
	},
	{title: '岳母', father: '祖父', mother: '祖母', wife: '岳父',
		son: {older: '大舅子', young: '小舅子', compare: '妻子'}, daughter: {older: '大姨子', young: '小姨子', compare: '妻子'},
		classify: '妻亲', alias: '丈母, 泰水',
	},
	{title: '外公', father: '外曾祖父', mother: '外曾祖母', wife: '外婆',
		son: {title: '舅舅'}, daughter: {title: '姨'},
		classify: '妻亲',
	},
	{title: '外婆', husband: '外公',
		son: {title: '舅舅'}, daughter: {title: '姨'},
		classify: '妻亲',
	},
	{title: '舅舅', father: '外公', mother: '外婆', wife: '舅母',
		son: {older: '表哥', young: '表弟', compare: '本人'}, daughter: {older: '表姐', young: '表妹', compare: '本人'},
		classify: '妻亲',
	},
	{title: '姨', father: '外公', mother: '外婆', husband: '姨夫',
		son: {older: '表哥', young: '表弟', compare: '本人'}, daughter: {older: '表姐', young: '表妹', compare: '本人'},
		classify: '妻亲',
	},
	{title: '表哥', wife: '表嫂',
		son: {title: '表侄'}, daughter: {title: '表侄女'},
		classify: '妻亲',
	},
	{title: '表弟', wife: '表嫂',
		son: {title: '表侄'}, daughter: {title: '表侄女'},
		classify: '妻亲',
	},
	{title: '表姐', husband: '表姐夫',
		son: {title: '表外甥'}, daughter: {title: '表外甥女'},
		classify: '妻亲',
	},
	{title: '表妹', husband: '表妹夫',
		son: {title: '表外甥'}, daughter: {title: '表外甥女'},
		classify: '妻亲',
	},
];
function init() {
	const count = countBy(TITLE_DEFAULT, (t) => t.title);
	for (const c in count) {
		if (c in count && count[c] > 1) {
			throw `称谓重复: ${c}`;
		}
	}
	for (const t of TITLE_DEFAULT) {
		if (!t.son) {
			throw `${t.title}缺少儿子称谓`;
		}
		if (!t.daughter) {
			throw `${t.title}缺少女儿称谓`;
		}
		if (t.son && t.son.title) {
			t.son.compare = '';
		}
		if (t.daughter && t.daughter.title) {
			t.daughter.compare = '';
		}
	}
}
init();
